#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Personal aliases and functions.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/aliases.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/aliases.zsh"
fi

# Machine-specific settings (untracked).
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.local"
fi
